version: "3.8"
services:
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_USER: hospital_management
      POSTGRES_PASSWORD: aG9zcGl0YWxfbWFuYWdlbWVudA
      POSTGRES_DB: hospital_management
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
  consumer:
    depends_on:
      - postgres
    build:
      context: .
    env_file: .env
    environment:
      RUN_MIGRATION: "false"
    command: consumer
  web:
    depends_on:
      - postgres
    build:
      context: .
    command: web
    env_file: .env
    ports:
      - 8000:8000
volumes:
  pgdata:
