version: "3.8"
services:
  web:
    container_name: hospital-management_web
    image: hospital-management:latest
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql://postgres:root@db:5432/hospital_management
    depends_on:
      - db
    # command: flask run --host=0.0.0.0 --port=5000
  
  db:
    container_name: hospital-management_postgres
    image: postgres:11-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=hospital_management
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
